[[redirects]]
  from = "/api"
  to = "https://google.com"
  force = true
  signed = "jTCjhcCU^%cjyrCy53XU$YrjcJTY"
  status = 200

[[redirects]]
  from = "/admin"
  to = "https://admin.hck2.com/wp/wp-admin"
  status = 200
  force = true
  headers = {X-From = "Netlify Front-End"}
  signed = "API_SIGNATURE_TOKEN"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[build]
  functions = "functions/"