backend:
  name: test-repo

publish_mode: editorial_workflow

site_url: localhost:8000

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog Posts
    label_singular: Blog Post
    folder: blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Hero Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown, hint: Main content goes here }

  - name: team-member
    label: Team Members
    label_singular: Team Member
    folder: team
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Hero Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown, hint: Main content goes here }