environments:
  staging: &staging
    logo_url: https://staging.hck2.dev/assets/svg/logo-square.svg
  production: &production
    logo_url: https://hck2.dev/assets/svg/logo-square.svg

backend:
  name: git-gateway
  repo: enlightenedpie/hck2-2020
  branch: master

publish_mode: editorial_workflow
site_url: https://hck2.dev
media_folder: static/assets
locale: en
<<: *staging

collections:
  - label: "Menus"
    name: "nav"
    editor:
      preview: false
    files:
      - label: "Header Menu"
        name: "header_nav"
        file: "content/nav/header.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Navigation"
            name: "nav_items"
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Path, name: path, widget: string }
              - {
                  label: Extra Classes,
                  name: classes,
                  widget: string,
                  required: false,
                }
      - label: "Footer Menu"
        name: "footer_nav"
        file: "content/nav/footer.yml"
        fields:
          - label: "Navigation"
            name: "nav_items"
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Path, name: path, widget: string }
              - {
                  label: Extra Classes,
                  name: classes,
                  widget: string,
                  required: false,
                }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "About Page"
        name: "about"
        file: "content/pages/about.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
  - name: blog
    label: Blog Posts
    label_singular: Blog Post
    folder: blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Hero Image, widget: image, required: false }
      - {
          name: body,
          label: Body,
          widget: markdown,
          hint: Main content goes here,
        }

  - name: team-member
    label: Team Members
    label_singular: Team Member
    folder: team
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Hero Image, widget: image, required: false }
      - {
          name: body,
          label: Body,
          widget: markdown,
          hint: Main content goes here,
        }
